### ISSUE TITLE
Generalize api 

### ISSUE THREAD

**Issue by ljonka** [wielebenwir/commons-api#1]
Hi, its great to see this project rise. 

It would be nice if all attributes are independent from specific pages, eg transforming 

Instead of "publish_on_velo" it would be nice to have an array like this:
"publish_on": [ 
{ 
  "api_endpoint_a": {
    'api_version': xy,
    'endpoint_url': 'https://...',
    'exchange_token': 'TOKEN',
    [...]
  }
}
]

It can be useful to add category and type attributes to be able to compare good language independent of local description.

**Comment by flegfleg** [comment]
Hi @ljonka, good point! It is a draft, your input would be useful. May i ask what platform/software/items you have in mind?  

@christianvoigt is currently working on implementing the the api into Commons Booking & velogistics, maybe you want to weigh in?

**Comment by christianvoigt** [comment]
I agree with you @ljonka that this should be open for other sites. 

The "publish_on"-field's purpose so far was only to allow users to publish Commons Booking Data via a Wordpress Rest Route, but at the same time stopping Velogistics from importing this data automatically into the central database, just because it is publicly available. So Velogistics would simply check if it is allowed to import the data, by looking for the Velogistics Api endpoint on the "publish_on" array. As we currently allow everyone to import data to Velogistics without creating any kind of user account we don't use exchange tokens. Could you elaborate what use cases you had in mind?

**Comment by ljonka** [comment]
Hi @flegfleg, hi @christianvoigt,

thanks for the fast reply.

The connection api could be useful to be able to use with other sharing platforms. 

1. The first case could be to just list available gods including booked / blocked times / days
2. in the next step it could be possible to book gods from one platform on another, but this can be tricky in many ways, while the communication should be clear and the process standardized in some way on the organization site

Lets assume the first  case: eg. at transition regensburg we have build such a system (https://www.transition-regensburg.de/verleih/) with already existing gods and a calendar for each item, when its booked/blocked. When another site will list the gods it would be possible, having a default api, to access the data by calling the api site, maybe comparable to a rss feed, but with all needed data for sharing gods. In this case it can be login/token less.

**Comment by christianvoigt** [comment]
> but this can be tricky in many ways

Yes exactly, so I think we should start by just making the data available. 

In my view the "publish_on" field is comparable to the 'noindex' meta field that prevents search engines from indexing a page. It is an easy way to allow the user fine-grained control about where to publish the data, without adding all the complexities associated with authentication. The downside is that it only works if the sites that consume this data respect this convention. 

Our idea for Velogistics.net is to allow other sites to call a url (e.g. velogistics.net/register?url=my-site.de/my-api-endpoint) to tell Velogistics to fetch the data. The data will be cached regularly and whenever this url gets called (obviously we have to make sure that this does not happen too often). Velogistics will then create a React-based map with all bikes that can be booked. Our plan is to make this map available as a widget so that other sites can simply add it to a page. If a user wants to see the details about a bike or wants to book the bike, she gets redirected to the original site.
